BlogWeb/BlogWeb/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin

from django.conf import settings
from django.conf.urls.static import static

from blog.feed import LatestEntriesFeed

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry


info_dict={
	'queryset':Entry.objects.all(),
	'date_field':'modified_time'
}

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^blog/',include("blog.urls")),
    url(r'',include("users.urls")),
    url(r'^latest/feed/$',LatestEntriesFeed()), #RSS订阅
    url(r'sitemap\.xml$',sitemap,{'sitemaps':{'blog':GenericSitemap(info_dict,priority=0.6)}},
    	name='django.contrib.sitemaps.views.sitemap'), #站点地图
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)    #添加图片的url

BlogWeb/apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2019-12-19 17:10:30
# @Author  : jinbo (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

from django.conf.urls import url

from . import views

app_name="blog"

urlpatterns=[
	url(r'^$',views.index,name='blog_index'),
	url(r'^(?P<blog_id>[0-9]+)/$',views.detail,name="blog_detail"),
	url(r'^category/(?P<category_id>[0-9]+)/$',views.catagory,name="blog_category"),
	url(r'^tag/(?P<tag_id>[0-9]+)/$',views.tag,name="blog_tag"),
	url(r'^search/$',views.search,name='blog_search'),
	url(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',views.archives,name='blog_archives'),
	url(r'^comments/(?P<blog_id>[0-9]+)/$',views.submit_comment,name="comments"),
]

BlogWeb/apps/blog/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from . import models
import markdown,pygments
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.


def detail(request,blog_id):
	entry=models.Entry.objects.get(id=blog_id)
	comments_list=models.UserComment.objects.filter(entry_id=blog_id)
	md=markdown.Markdown(extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc',
		])
	entry.body=md.convert(entry.body)
	entry.toc=md.toc
	entry.increase_visiting()#访问量加一
	return render(request,"blog/detail.html",locals())

def make_paginator(objects,page,num=10):
	paginator=Paginator(objects,num)
	try:
		object_list=paginator.page(page)
	except PageNotAnInteger:
		object_list=paginator.page(1)
	except EmptyPage:
		object_list=paginator.page(paginator.num_pages)

	return object_list,paginator


def pagination_data(paginator,page):
	"""
	用于自定义展示分页页码的方法
	:param paginator: Paginator类的对象
	:param page: 当前请求的页码
	:return: 一个包含所有页码和符号的字典
	"""
	if paginator.num_pages==1:
		# 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
		return {}
	# 当前页左边连续的页码号，初始值为空
	left={}
	# 当前页右边连续的页码号，初始值为空
	right={}

	#标识第一页码后是否需要显示省略号
	left_has_more=False

	#标识最后一页页码前是否需要显示省略号
	right_has_more=False
	# 标示是否需要显示第 1 页的页码号。
	# 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
	# 其它情况下第一页的页码是始终需要显示的。
	# 初始值为 False
	first=False

	#标识是否需要显示最后一页的页码号
	last=False

	#获得用户当前请求的页码号
	try:
		page_number=int(page)
	except ValueError:
		page_number=1
	except:
		page_number=1

	#获得分页后的总页数
	total_pages=paginator.num_pages

	#获得整个分页页码列表，比如分了四页，那么就是[1,2,3,4]
	page_range=paginator.page_range

	if page_number==1:
		# 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
		# 此时只要获取当前页右边的连续页码号，
		# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
		# 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
		right=page_range[page_number:page_number+4]

		#如果最右边的页码比最后一页的页码号减去1还要小，
		#说明最右边的页码号和最后一页的页码号之间还有其他页码，因此需要显示省略号，通过right_has_more来指示
		if right[-1]<total_pages-1:
			right_has_more=True

		#如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码中不包含最后一页的页码
		#所以需要显示最后一页的页码号，通过last来指示
		if right[-1]<total_pages:
			last=True
	elif page_number==total_pages:
		# 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
		# 此时只要获取当前页左边的连续页码号。
		# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
		# 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
		left=page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

		# 如果最左边的页码号比第 2 页页码号还大，
		# 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
		if left[0] > 2:
			left_has_more = True
		# 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
		# 所以需要显示第一页的页码号，通过 first 来指示
		if left[0] > 1:
			first = True
	else:
		#用户请求的既不是最后一页，也不是第一页，则获取当前页码左右两边连续页码号
		#这里获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
		left=page_range[(page_number-3) if (page_number-3)>0 else 0:page_number-1]
		right=page_range[page_number:page_number+2]

		#是否需要显示最后一页和最后一页的省略号
		if right[-1]<total_pages-1:
			right_has_more=True
		if right[-1]<total_pages:
			last=True

		#是否需要显示第一页和第一页后面的省略号
		if left[0]>2:
			left_has_more=True
		if left[0]>1:
			first=True

	data={
		'left':left,
		'right':right,
		'left_has_more':left_has_more,
		'right_has_more':right_has_more,
		'first':first,
		'last':last,
	}
	return data

def index(request):
	entries=models.Entry.objects.all()
	categories=models.Category.objects.all()
	page=request.GET.get('page',1)
	entry_list,paginator=make_paginator(entries,page)
	page_data=pagination_data(paginator,page)
	return render(request,"blog/index.html",locals())
	# return redirect(reverse("blog:blog_index",kwargs={"user_name":user_name}))


def catagory(reqeust,category_id):
	categories=models.Category.objects.all()
	c=models.Category.objects.get(id=category_id)
	entries=models.Entry.objects.filter(category=c)
	page=reqeust.GET.get('page',1)
	entry_list,paginator=make_paginator(entries,page)
	page_data=pagination_data(paginator,page)

	return render(reqeust,'blog/index.html',locals())

def tag(request,tag_id):
	t=models.Tag.objects.get(id=tag_id)
	if t.name == '全部':
		entries=models.Entry.objects.all()
	else:
		entries=models.Entry.objects.filter(tags=t)
	page=request.GET.get('page',1)
	entry_list,paginator=make_paginator(entries,page)
	page_data=pagination_data(paginator,page)
	return render(request,'blog/index.html',locals())

def search(request):
	keyword=request.GET.get('keyword',None)
	if not keyword:
		error_msg="请输入关键字"
		return render(request,'blog/index.html',locals())

	entries=models.Entry.objects.filter(Q(title__icontains=keyword)
										|Q(body__icontains=keyword)
										|Q(abstract__icontains=keyword))
	page=request.GET.get('page',1)
	entry_list,paginator=make_paginator(entries,page)
	page_data=pagination_data(paginator,page)
	return render(request,'blog/index.html',locals())


def archives(request,year,month):
	entries=models.Entry.objects.filter(created_time__year=year,created_time__month=month)
	page=request.GET.get('page',1)
	entry_list,paginator=make_paginator(entries,page)
	page_data=pagination_data(paginator,page)
	return render(request,'blog/index.html',locals())



def submit_comment(request,blog_id):
	comment=models.UserComment()
	post=request.POST
	comment.title=post.get("title",None)
	comment.email=post.get("email")
	comment.website=post.get("website")
	comment.content=post.get("content")
	comment.entry=models.Entry.objects.get(id=blog_id)
	comment.save()

	return redirect(reverse("blog:blog_detail",kwargs={"blog_id":blog_id}))

BlogWeb/extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.rel, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str if six.PY3 else basestring
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str if six.PY3 else basestring
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):
        return super(DetailAdminView, self).get_media() + self.form_obj.media + \
            self.vendor('xadmin.page.form.js', 'xadmin.form.css')

    @filter_hook
    def get_field_result(self, field_name):

BlogWeb/apps/blog/templates/blog/articlelist.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Examples</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    
</body>
</html>

BlogWeb/apps/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}博客详情页{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static '/css/github.css' %}">
 <link rel="stylesheet" href="{% static '/css/detail.css' %}">
{% endblock %}

 {% block container-leftcolumn %}
    {% include 'left_side_bar.html' %}
{% endblock %}


{% block container-middlecolumn %}
	<div class="blog-content-box">
		<div class="article-header-box">
			<div class="article-title-box">
				<h1 class="title-article">{{ entry.title }}</h1>
			</div>
			<div class="article-info-box">
				<div class="article-bar-top">
					<span class="article-type">原创{{ entry.get_articleType }}</span>
					<a class="follow-nickname" href="">{{ entry.author.username }}</a>
					<span class="create_time">发布于{{ entry.created_time }}</span>
					<span class="read-count">阅读数 {{ entry.visiting }}</span>
				</div>
			</div>
			<div class="slide-content-box">
				<div class="article-catgory">
					<span class="label">文章分类:</span>
					{% for category in entry.category.all %}
					<a class="article-catgory-link" href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
					{% endfor %}
				</div>
				<div class="article-Tag">
					{% for tag in entry.tags.all %}
					<span class="label">文章标签:</span>
					<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
					{% endfor %}
				</div>
				<div class="article-copyright">
					<span>版权声明：本文为博主原创文章，遵循
					<a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener"> CC 4.0 BY-SA </a>
					版权协议，转载请附上原文出处链接和本声明。
					</span>
					<div class="article-source-link2222">
                                本文链接：<a href="{{ entry.get_absolute_url }}">{{ entry.get_absolute_url }}</a>
                            </div>
				</div>
			</div>
		</div>
		<!-- 内容顶部结束 -->

		<article class="articleArea">
			<div class="article-content">
				<p>
					{{ entry.toc|safe }}
					{{ entry.body|safe }}
					<!-- {{ entry.body }} -->
				</p>
				
			</div>
		</article>
	</div>
	<div class="article-comment-box">
		<div class="article-comment-list">
			<dl>
				{% for comment in comments_list %}
				<dt>
					发件人：{{ comment.title }}
				</dt>
				<dd>
					{{ comment.content }}
				</dd>
				{% endfor %}
			</dl>
		</div>
		<div class="article-comment-editor">
			<form class="commentform" method="post" action="{% url 'blog:comments' entry.id %}">
				<div class="top-comment-title">
					<label class="label-title">评论标题:</label>
					<input class="input-title" type="text" name="title">
				</div>
				<div class="top-comment-email">
					<label class="label-email">邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;件:</label>
					<input class="input-email" type="text" name="email">
				</div>
				<div class="top-comment-content">
					<textarea name="content" placeholder="想对作者说点什么"></textarea>
				</div>
				<input type="hidden" name="website" value="{{ entry.get_absolute_url }}">
				<input type="submit" name="submit" value="发表评论">
				{% csrf_token %}
			</form>
		</div>
	</div>

{% endblock %}

   {% block container-rightcolumn %}
	   	{% if entry.toc|safe %}
	         <div class="rightcolumn-toc">
	            <h3>目录</h3>
	             {{ entry.toc|safe }}
	         </div>
	    {% endif %}
  {% endblock %}

BlogWeb/apps/blog/templates/blog/left_side_bar.html
{% load blog_tags %}
{% load user_tags %}
{% load staticfiles %}
	<!-- 个人信息栏 -->
    	<div class="personal-info">
    		<div class="toparea">
    			<a href="index.html">
    				<ul>
    				<li>
    					{% if request.user.is_authenticated %}
    					<img class="img-circle" src="{{ request.user.image }}">
    					{% else %}
    					<img class="img-circle" src="{% static 'images/default_head_img.gif' %}">
    					{% endif %}
    				</li>
    				<li style="text-align: left;width:60%;margin-top: 6px;"><b>{{ request.user.nick_name }}</b></li>
    				<li style="text-align: left;width:60%;color: rgb(19,197,248);font-size: 15px;"><b>个人主页></b></li>
    				</ul>
    			</a>
    		</div>
    		<div class="personalsign">
    			<ul>
    				<li class="signinfo">博主是一个爱捣鼓，爱钻研爱学习的码农，梦想是采菊东篱下，悠然见南山</li>
    			</ul>
    		</div>
    		<div class="middlearea">
    			<!-- 文章，粉丝，访问量相关信息 -->
    			<div class="ulinfo">
						<dl id="middlearea-article">
							<a href=""><dt>文章</dt><dd>{% get_total_entrycount %}</dd></a>
						</dl>
						<dl id="middlearea-fensi">
							<dt>粉丝</dt><dd>0</dd>
						</dl>
						<dl id="middlearea-pinglun">
							<dt>评论</dt><dd>0</dd>
						</dl>
						<dl id="middlearea-visit">
							<dt>访问</dt><dd>0</dd>
						</dl>
						<dl id="middlearea-zan">
							<dt>获赞</dt><dd>0</dd>
						</dl>
    			</div>

    			<!-- 社交联系信息 -->
    			<div class="relation">
    				<dl id="qq">
    					<a href="http://shang.qq.com/wpa/qunwpa?idkey=77fbfb6138ce6e26e4289d15725e5df9d66bf298d17e881f2abd777334505255" target="_blank">
    						<dt><img class="imgSvg" src="{% static 'images/qq.svg' %}"></dt>
    						<dd>QQ群</dd>
    					</a>
    				</dl>
    				<dl id="github">
    					<a href="">
    						<dt><img class="imgSvg" src="{% static 'images/githubsvg.svg' %}"></dt>
    						<dd>github</dd>
    					</a>
    				</dl>
    				<dl id="gongzhonghao">
    					<a href="">
    						<dt><img class="imgSvg" src="{% static 'images/weixin.svg' %}"></dt>
    						<dd>公众号</dd>
    					</a>
    				</dl>
    			</div>
    		</div>
            <div class="bottom-guanzhu">
                <div class="guanzhu-item">
                    <ul>
                        <li class="guanzhu-li"><button name="btnGuanzhu">关注</button></li>
                        <li class="sendmsg-li"><button name="btnSendMessage">私信</button></li>
                    </ul>
                </div>
            </div>
    	</div>
    	<!-- 个人信息结束 -->


<!-- 最新文章 -->
<div class="asideArchive">
			<h3 class="aside-title">最新文章</h3>
			{% get_recent_entries as recent_entry_list %}
		<div class="aside-content">
			<div class="lately-article">
				{% for entry in recent_entry_list %}
				<dl>
					<a href="{{ entry.get_absolute_url }}">
						<dt>{{ entry.title }}</dt> 
						<dd>{{ entry.created_time|date:"Y年m月d日" }}</dd> 
					</a>
				</dl>
				{% endfor %}
			</div>
		</div>
</div>

	<!-- 分类 -->
<div class="asideArchive">
	<h3 class="aside-title">分类</h3>
    {% get_categories as category_list %}
	<div class="aside-content">
		<ul class="archive-list">
			{% for category in category_list %}
			<li>
				<a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}
					<span class="count-float-right">{% get_entry_count_of_category category.name %}篇</span>
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
	<p class="text-center">
		<a href="">展开</a>
	</p>
</div>

<!-- 归档 -->
<div class="asideArchive">
	<h3 class="aside-title">归档</h3>
	{% archives as date_list %}
	<div class="aside-content">
		<ul class="archive-list">
			{% for date in date_list %}
			<li>
				<a href="{% url 'blog:blog_archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月
					<span class="count-float-right">{% get_entry_count_of_date date.year date.month %}篇</span>
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
	<p class="text-center">
		<a href="">展开</a>
	</p>
</div>

<!-- 热门文章 -->
<div class="asideArchive">
			<h3 class="aside-title">热门文章</h3>
			{% get_popular_entries as popular_entry_list %}
		<div class="aside-content">
			<div class="lately-article">
				{% for entry in popular_entry_list %}
				<dl style="border: none;">
					<a href="{{ entry.get_absolute_url }}">
						<dt>{{ entry.title }}</dt> 
						<dd>阅读数：{{ entry.visiting }}</dd> 
					</a>
				</dl>
				{% endfor %}
			</div>
		</div>
</div>

<!-- 标签 -->
<div class="asideArchive">
	<h3 class="aside-title">标签云:</h3>
	{% get_tags as tag_list %}
	<div class="aside-content">
		<ul class="archive-list">
			{% for tag in tag_list %}
			<li style="border: 1px solid #aaa;background-color:#fff;border-radius: 3px; display: inline-block;margin-right: 3px;
			-webkit-margin-after:1em;padding:2px;">
				<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>


{% block toc %}
{% endblock %}